# Generated by Django 2.1.dev20180420150614 on 2018-04-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvapp', '0003_athlete_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='first_name',
        ),
    ]
