# Generated by Django 2.1.dev20180420150614 on 2018-05-02 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvapp', '0006_auto_20180502_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='time',
            new_name='date',
        ),
    ]
